name: Android CI

on:
  schedule:
    - cron: '0 22 * * *' # run at 7 AM UTF+9

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    # Get Current Date
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    # Runs a Android Build
    - name: Build APK
      run: bash ./gradlew assembleDebug --stacktrace

    - name: Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.3.4
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: tester
        file: app/build/outputs/apk/debug/app-debug.apk
